import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

import type { Metadata } from "next";
import { inter, poppins } from "./fonts/fonts";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ReduxProvider from "@/redux/ReduxProvider";
import { DisplayModal } from "@/components/modal/DisplayModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} ${poppins.variable} antialiased`}>
          <ReduxProvider>
            <DisplayModal />
            <Navbar />
            {children}
            {modal}
          </ReduxProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
