import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <header className="p-3 bg-green-300">header</header>
        <main className="flex-1">{children}</main>
        <footer className="bg-blue-900 p-2">Footer</footer>
      </body>
    </html>
  );
}
