import { Metadata } from "next";

import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";
import { inter, oswald, playfair, titillium } from "./fonts/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${oswald.variable} ${titillium.variable}  ${playfair.variable} antialiased`}
    >
      <body className="font-inter">{children}</body>
    </html>
  );
}
